from datetime import datetime
from typing import Optional
from sqlalchemy import String, Boolean, text, ForeignKey, Index, func
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy import DateTime
from app.database import Base

class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    tenant_id: Mapped[Optional[str]] = mapped_column(UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"))
    
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    designation: Mapped[Optional[str]] = mapped_column(String(100))
    phone: Mapped[Optional[str]] = mapped_column(String(20))
    
    role: Mapped[str] = mapped_column(String(30), nullable=False)
    
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    last_login_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    
    # Legacy single-session refresh state, superseded by refresh_sessions (one row per
    # login). No longer read or written; kept so the migration stays additive.
    refresh_token_hash: Mapped[Optional[str]] = mapped_column(String(255))
    refresh_token_exp: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=text("now()"))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=text("now()"))

# Logins/signups match emails case-insensitively (lower(email) = normalized input). Not
# unique: older rows may differ only by case; new rows are stored lowercase, so the unique
# constraint on email already rejects new duplicates.
Index("ix_users_email_lower", func.lower(User.email))


class RefreshSession(Base):
    """One row per login (tab/device). The refresh token rotates within its row, so a second
    login no longer kills the first one. Presenting a token of this session that was already
    rotated away means it was copied: the whole session is revoked (reuse detection)."""
    __tablename__ = "refresh_sessions"

    # Generated by the app (no server default): the id goes into the refresh JWT ("sid")
    # before the row is flushed
    id: Mapped[str] = mapped_column(UUID(as_uuid=True), primary_key=True)
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # bcrypt hash of the CURRENT refresh token of this session
    token_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    revoked_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    revoked_reason: Mapped[Optional[str]] = mapped_column(String(30))  # LOGOUT | TOKEN_REUSE

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=text("now()"))
    last_used_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
