"""
Generate a SAR report from the mock alert and SAVE it as files you can open:
  outputs/sar_<txn>.json   -> the canonical structured record (narrative + JSON)
  outputs/sar_<txn>.pdf    -> the human-readable, bank-facing report (rehydrated PII)

Full RAG pipeline, DB-free, uses the Groq key from backend/.env.
Run from repo root:  python scripts/generate_sar_report.py
"""
import json
import os
import sys
import tempfile
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKEND = os.path.join(ROOT, "backend")
sys.path.insert(0, BACKEND)
os.chdir(BACKEND)  # so backend/.env (Groq key) loads

os.environ.setdefault("CHROMA_PERSIST_DIR", tempfile.mkdtemp(prefix="chroma_rpt_"))
import app.services.chroma_client as cc  # noqa: E402
cc._PERSIST_DIR = os.environ["CHROMA_PERSIST_DIR"]

from app.config import settings                                       # noqa: E402
from app.services.schema_normalizer import normalize_payload          # noqa: E402
from app.services.pii_masker import mask_payload                      # noqa: E402
from app.services.compliance_analyzer import analyze                  # noqa: E402
from app.data.schema_presets import SCHEMA_PRESETS                    # noqa: E402
from app.services import document_ingestion_service as dis            # noqa: E402
from app.services.rag_retrieval_service import retrieve_regulatory_context  # noqa: E402
from app.services.llm_agent import generate_sar_core                  # noqa: E402

from reportlab.lib.pagesizes import A4                                # noqa: E402
from reportlab.lib.units import mm                                    # noqa: E402
from reportlab.lib.enums import TA_JUSTIFY                            # noqa: E402
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle  # noqa: E402
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,  # noqa: E402
                                Table, TableStyle, HRFlowable)
from reportlab.lib import colors                                      # noqa: E402

PDF_IN = os.path.join(ROOT, "testing", "corpus", "aegis_bank_aml_policy.pdf")
MOCK = os.path.join(ROOT, "testing", "inputs", "alert_structuring_intlwire.json")
OUTDIR = os.path.join(ROOT, "outputs")
TENANT = "client_0"   # dummy/test client (real clients start at client_1)


def render_pdf(path, record):
    styles = getSampleStyleSheet()
    H = ParagraphStyle("H", parent=styles["Heading2"], fontName="Helvetica-Bold",
                       fontSize=12, textColor=colors.HexColor("#0B2E4F"), spaceBefore=12, spaceAfter=6)
    body = ParagraphStyle("B", parent=styles["BodyText"], fontSize=10, leading=15, alignment=TA_JUSTIFY)
    story = []
    story.append(Paragraph("SUSPICIOUS TRANSACTION REPORT (STR)", ParagraphStyle(
        "T", parent=styles["Title"], fontSize=18, textColor=colors.HexColor("#0B2E4F"))))
    story.append(Paragraph("Aegis Bank Limited &nbsp;|&nbsp; Generated by Aegis AML", styles["Normal"]))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#14507F"),
                            spaceBefore=6, spaceAfter=8))
    meta = Table([
        ["SAR ID", record["sar_id"]],
        ["Transaction ID", record["transaction_id"]],
        ["Generated", record["generated_at"]],
        ["Composite Risk Score", str(record["risk_score"])],
        ["Status", "PENDING OFFICER REVIEW"],
    ], colWidths=[45 * mm, 120 * mm])
    meta.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 9.5),
        ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 9.5),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D6DEE6")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#F4F7FA"), colors.white]),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(meta)

    story.append(Paragraph("1. Narrative", H))
    for para in record["narrative"].split("\n"):
        if para.strip():
            story.append(Paragraph(para.strip(), body))
            story.append(Spacer(1, 4))

    indicators = record["structured"].get("key_indicators", []) if isinstance(record["structured"], dict) else []
    if indicators:
        story.append(Paragraph("2. Key Indicators &amp; Regulatory Basis", H))
        rows = [["Indicator", "Regulation", "Description"]]
        for ind in indicators:
            if isinstance(ind, dict):
                rows.append([ind.get("indicator", ""), ind.get("regulation", ""), ind.get("description", "")])
            else:
                rows.append([str(ind), "", ""])
        tbl = Table(rows, colWidths=[35 * mm, 40 * mm, 90 * mm])
        tbl.setStyle(TableStyle([
            ("FONT", (0, 0), (-1, -1), "Helvetica", 8.5),
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8.5),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B2E4F")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D6DEE6")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(tbl)

    action = record["structured"].get("recommended_action") if isinstance(record["structured"], dict) else None
    if action:
        story.append(Paragraph("3. Recommended Action", H))
        story.append(Paragraph(str(action), body))

    if record.get("sources"):
        story.append(Paragraph("4. Regulatory Sources Cited", H))
        for s in record["sources"]:
            story.append(Paragraph(f"&bull;&nbsp; {s}", body))

    story.append(Spacer(1, 14))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#D6DEE6")))
    story.append(Paragraph("CONFIDENTIAL - Auto-generated draft. Must be reviewed and "
                           "approved by the Principal Officer before filing with FIU-IND.",
                           ParagraphStyle("F", parent=styles["Normal"], fontSize=8, textColor=colors.grey)))
    SimpleDocTemplate(path, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                      topMargin=16 * mm, bottomMargin=16 * mm).build(story)


def main():
    os.makedirs(OUTDIR, exist_ok=True)
    chunks = dis.build_chunks(PDF_IN, "Aegis Bank AML/CFT Policy",
                              "aegis_bank_aml_policy.pdf", "aegis-policy-1")
    dis.index_document(TENANT, chunks)

    raw = json.load(open(MOCK, encoding="utf-8"))
    preset = SCHEMA_PRESETS["STANDARD_FINTECH"]
    norm = normalize_payload(raw, preset["field_map"])
    masked, token_map = mask_payload(norm, preset["pii_fields"])
    results = [r for r in analyze(norm) if r["triggered"]]
    base = max(0, min(100, int(float(norm.get("risk_score") or 0))))
    score = min(100, base + sum(20 if r["confidence"] == "HIGH" else 10 for r in results))

    compliance_results = [{"rule_name": r["rule_name"], "triggered": True} for r in results]
    hits = retrieve_regulatory_context(TENANT, masked, compliance_results)
    out = generate_sar_core(masked, score, settings.GROQ_MODEL, retrieved_chunks=hits)

    # rehydrate PII for the bank-facing report
    rehydrated = out["narrative"]
    for token, original in token_map.items():
        rehydrated = rehydrated.replace(token, str(original))

    txn = norm.get("transaction_id", "unknown")
    record = {
        "sar_id": "SAR-" + datetime.now().strftime("%Y%m%d-%H%M%S"),
        "transaction_id": txn,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "risk_score": score,
        "triggered_rules": [r["rule_name"] for r in results],
        "narrative": rehydrated,                 # real PII (bank copy)
        "narrative_masked": out["narrative"],    # token version (internal)
        "structured": out["structured"],
        "sources": [c["section"] for c in out["used_chunks"]],
    }

    json_path = os.path.join(OUTDIR, f"sar_{txn}.json")
    pdf_path = os.path.join(OUTDIR, f"sar_{txn}.pdf")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(record, f, indent=2, ensure_ascii=False)
    render_pdf(pdf_path, record)

    print("Saved:")
    print("  JSON:", json_path)
    print("  PDF :", pdf_path)
    print("\nTriggered:", ", ".join(record["triggered_rules"]))
    print("Sources cited:", ", ".join(record["sources"][:4]), "...")


if __name__ == "__main__":
    main()
