"""
Regenerate the ENTIRE mock/testing environment from scratch.

Writes everything under testing/ so the mock data is fully reproducible after a
wipe (`python scripts/reset.py --barebone`):

  testing/corpus/aegis_bank_aml_policy.pdf      (built by testing/build_policy.py)
  testing/inputs/alert_structuring_intlwire.json (the generation demo input)
  testing/clients/client_0/policy.pdf            (copy of the corpus policy)
  testing/clients/client_0/config.json           (eval answer key)
  testing/clients/client_0/alerts/01..05.json    (eval test alerts)

Run:  python scripts/seed_testing.py
The 'real' side (production/) is intentionally left empty.
"""
import json
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TESTING = os.path.join(ROOT, "testing")

# --- demo input used by the generation scripts ---
DEMO_INPUT = {
    "customer": {"full_name": "Rohan Mehta", "id": "CUST-884213"},
    "account": {"number": "5012-7788-2231"},
    "txn": {"ref_id": "TXN-2026-0416-99001", "amount": 945000, "currency": "INR",
            "type": "INTERNATIONAL_WIRE", "direction": "OUTBOUND",
            "timestamp": "2026-04-16T11:42:07+05:30"},
    "counterparty": {"account": "AE070331234567890123456",
                     "name": "Gulf Horizon Trading FZE", "bank": "Emirates NBD"},
    "metadata": {"ip": "203.0.113.57", "device_id": "dev-9f3c1a77"},
    "risk": {"score": 88, "reason": "Large outbound transfer just below the reporting threshold to a newly added overseas beneficiary."},
}

# --- client_0 (dummy) eval config: the per-client answer key ---
CLIENT0_CONFIG = {
    "tenant_id": "client_0",
    "display_name": "DUMMY/TEST CLIENT (client_0 — synthetic Aegis Bank). Real clients start at client_1.",
    "policy_pdf": "policy.pdf",
    "schema_preset": "STANDARD_FINTECH",
    "always_relevant": ["5.1"],
    "_comment": "PER-CLIENT dummy answer key. Regenerated by scripts/seed_testing.py. rule_to_section uses THIS client's policy section numbers.",
    "rule_to_section": {
        "Structuring / Smurfing": "4.1",
        "Rapid Movement of Funds": "4.2",
        "Large Round Number": "4.3",
        "Dormant Account Activation": "4.4",
        "High Risk Transaction Type": "4.5",
        "High Velocity": "4.6",
        "High Risk Counterparty": "4.7",
        "Risk Score Threshold Exceeded": "4.8",
    },
}

# --- client_0 eval alerts (cover all 8 typologies) ---
CLIENT0_ALERTS = {
    "01_structuring_intlwire.json": {
        "customer": {"full_name": "Rohan Mehta", "id": "CUST-884213"},
        "account": {"number": "5012-7788-2231"},
        "txn": {"ref_id": "TXN-EVAL-01", "amount": 945000, "currency": "INR",
                "type": "INTERNATIONAL_WIRE", "direction": "OUTBOUND",
                "timestamp": "2026-04-16T11:42:07+05:30"},
        "counterparty": {"account": "AE070331234567890123456",
                         "name": "Gulf Horizon Trading FZE", "bank": "Emirates NBD"},
        "metadata": {"ip": "203.0.113.57", "device_id": "dev-9f3c1a77"},
        "risk": {"score": 88, "reason": "Large outbound transfer just below the reporting threshold to a newly added overseas beneficiary."},
    },
    "02_dormant_velocity.json": {
        "customer": {"full_name": "Sunita Rao", "id": "CUST-551200"},
        "account": {"number": "6101-2233-9090"},
        "txn": {"ref_id": "TXN-EVAL-02", "amount": 250000, "currency": "INR",
                "type": "TRANSFER", "direction": "OUTBOUND",
                "timestamp": "2026-05-02T09:15:00+05:30"},
        "counterparty": {"account": "1122-3344-5566", "name": "Anil Kumar", "bank": "HDFC Bank"},
        "metadata": {"ip": "198.51.100.22", "device_id": "dev-2210bbef"},
        "risk": {"score": 92, "reason": "Dormant account suddenly reactivated with unusually high velocity of outbound transfers."},
    },
    "03_roundnum_crypto.json": {
        "customer": {"full_name": "Vikram Shah", "id": "CUST-330815"},
        "account": {"number": "7788-1100-4455"},
        "txn": {"ref_id": "TXN-EVAL-03", "amount": 500000, "currency": "INR",
                "type": "CRYPTO_PURCHASE", "direction": "OUTBOUND",
                "timestamp": "2026-05-10T18:05:30+05:30"},
        "counterparty": {"account": "EXCH-99812", "name": "CoinExchange Pte", "bank": "CoinExchange Pte"},
        "metadata": {"ip": "192.0.2.71", "device_id": "dev-77aa12cd"},
        "risk": {"score": 70, "reason": "Customer purchased virtual assets in an exact round-figure amount."},
    },
    "04_refund_counterparty.json": {
        "customer": {"full_name": "Meera Iyer", "id": "CUST-770450"},
        "account": {"number": "9001-5566-7788"},
        "txn": {"ref_id": "TXN-EVAL-04", "amount": 320000, "currency": "INR",
                "type": "REFUND", "direction": "INBOUND",
                "timestamp": "2026-05-14T13:20:10+05:30"},
        "counterparty": {"account": "SHL-0098", "name": "Opaque Holdings", "bank": "Shell Bank Ltd"},
        "metadata": {"ip": "203.0.113.200", "device_id": "dev-55cd91aa"},
        "risk": {"score": 60, "reason": "Large refund processed shortly after credit; counterparty institution could not be verified."},
    },
    "05_hawala_structuring.json": {
        "customer": {"full_name": "Imran Sheikh", "id": "CUST-119077"},
        "account": {"number": "4455-6677-2200"},
        "txn": {"ref_id": "TXN-EVAL-05", "amount": 870000, "currency": "INR",
                "type": "HAWALA", "direction": "OUTBOUND",
                "timestamp": "2026-05-20T20:45:00+05:30"},
        "counterparty": {"account": "NA", "name": "Unknown Intermediary", "bank": "Local Agent"},
        "metadata": {"ip": "198.51.100.88", "device_id": "dev-9001ffaa"},
        "risk": {"score": 72, "reason": "Funds moved via an informal value-transfer arrangement in an amount just below the threshold."},
    },
}


def _write_json(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)
    print(f"  wrote {os.path.relpath(path, ROOT)}")


def main():
    print("Seeding the mock/testing environment:")
    # 1. build the synthetic policy PDF
    subprocess.run([sys.executable, os.path.join(TESTING, "build_policy.py")], check=True)
    corpus_pdf = os.path.join(TESTING, "corpus", "aegis_bank_aml_policy.pdf")

    # 2. generation demo input
    _write_json(os.path.join(TESTING, "inputs", "alert_structuring_intlwire.json"), DEMO_INPUT)

    # 3. client_0 eval: config, policy copy, alerts
    c0 = os.path.join(TESTING, "clients", "client_0")
    _write_json(os.path.join(c0, "config.json"), CLIENT0_CONFIG)
    os.makedirs(c0, exist_ok=True)
    shutil.copyfile(corpus_pdf, os.path.join(c0, "policy.pdf"))
    print(f"  copied {os.path.relpath(os.path.join(c0, 'policy.pdf'), ROOT)}")
    for name, obj in CLIENT0_ALERTS.items():
        _write_json(os.path.join(c0, "alerts", name), obj)

    print("Done — mock environment regenerated under testing/. (production/ stays empty.)")


if __name__ == "__main__":
    main()
